artifacts: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/13FrqXYmVkaBVKx0b0NuvBRvAVo5r3LWk/view?usp=sharing
  local_data_zip: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  dataset_dir: artifacts/data_ingestion/gi_tract_data
  train_dir: artifacts/data_ingestion/gi_tract_data/train
